version: "3"
services:
  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: accounts
    ports:
      - "8081:8081"
    networks:
      - db-network
      - ads-network
      - transactions-network
  ads:
    build:
      context: .
      dockerfile: ads/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: ads
    ports:
      - "8082:8082"
    networks:
      - db-network
      - ads-network
    links:
      ##allows us to reach the account microservice from ads microservice
      - "accounts"
  transactions:
    build:
      context: .
      dockerfile: transactions/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: transactions
    ports:
      - "8083:8083"
    networks:
      - db-network
      - transactions-network
    links:
      ##allows us to reach the account microservice from ads microservice
      - "accounts"
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    networks:
      - db-network

networks:
  db-network:
  ads-network:
  transactions-network:
