version: "2"
services:
  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: accounts
    ports:
      - 8802:8081
  ads:
    build:
      context: .
      dockerfile: ads/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: ads
    ports:
      - 8800:8081
  transactions:
    build:
      context: .
      dockerfile: transactions/Dockerfile
    restart: always
    volumes:
      - .:/go/src/golangmicroservices
    container_name: transactions
    ports:
      - 8801:8081
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
